/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'treemodel',
        'TermModel'
    ],
    stores: [
        'myontostore',
        'ConTreeStore',
        'ConBodyTreeStore',
        'InsTreeStore',
        'RelTreeStore',
        'ConTermStore',
        'RelTermStore',
        'InsBodyTreeStore',
        'InsTermStore',
        'RelBodyTreeStore',
        'AttTreeStore',
        'AttBodyTreeStore',
        'AttTermForClass',
        'AttTermValueForClass',
        'ConTermOnlyStore',
        'conSearchStore',
        'conSerarchStoreBak'
    ],
    views: [
        'MyViewport',
        'MyWindow',
        'MyWindow1',
        'MyWindow2',
        'MyWindow3',
        'MyWindow4',
        'MyWindow5',
        'MyWindow6',
        'MyWindow7',
        'MyWindow8',
        'MyWindow10',
        'MyWindow9',
        'MyWindow11',
        'MyWindow12'
    ],
    autoCreateViewport: true,
    name: 'MyApp'
});
