/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'absolute'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    x: 130,
                    y: 110,
                    height: 313,
                    id: 'loginform',
                    width: 460,
                    layout: {
                        type: 'absolute'
                    },
                    bodyPadding: 10,
                    title: '本体管理系统登录',
                    jsonSubmit: false,
                    items: [
                        {
                            xtype: 'textfield',
                            x: 90,
                            y: 70,
                            id: 'userfield',
                            fieldLabel: '用户名：'
                        },
                        {
                            xtype: 'textfield',
                            x: 90,
                            y: 120,
                            id: 'pwdfield',
                            fieldLabel: '密码',
                            inputType: 'password'
                        },
                        {
                            xtype: 'button',
                            x: 180,
                            y: 190,
                            id: 'login',
                            text: '登录',
                            listeners: {
                                click: {
                                    fn: me.onLoginClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            x: 290,
                            y: 190,
                            id: 'regist',
                            href: '/ontotest/register/app.html',
                            text: '注册'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onLoginClick: function(button, e, eOpts) {

        Ext.getCmp('loginform').getForm().submit({
            clientValidation: true,

            url: '/ontotest/userlogin',

            params: {
                username: Ext.getCmp('userfield').getValue(),
                password: Ext.getCmp('pwdfield').getValue()

            },
            success: function(form, action) {
                Ext.Msg.alert('Success', action.result.msg);
                window.location.href="/ontotest/ontoadmin/app.html";

            },
            failure: function(form, action) {
                switch (action.failureType) {
                    case Ext.form.action.Action.CLIENT_INVALID:
                    Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
                    break;
                    case Ext.form.action.Action.CONNECT_FAILURE:
                    Ext.Msg.alert('Failure', 'Ajax communication failed');
                    break;
                    case Ext.form.action.Action.SERVER_INVALID:
                    Ext.Msg.alert('Failure', action.result.msg);
                }
            }
        });
    }

});