/*
 * File: app/view/MyWindow1.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyWindow1', {
    extend: 'Ext.window.Window',

    height: 250,
    id: 'AddRelOfCon',
    width: 400,
    title: 'My Window',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 216,
                    id: 'submitform',
                    width: 387,
                    layout: {
                        type: 'absolute'
                    },
                    bodyPadding: 10,
                    title: '添加概念关系',
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            x: 10,
                            y: 30,
                            id: 'conrel',
                            fieldLabel: '关系',
                            name: 'relation',
                            store: 'RelTermStore'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            x: 10,
                            y: 70,
                            id: 'conval',
                            fieldLabel: '关系值',
                            name: 'relationval',
                            store: 'ConTermOnlyStore'
                        },
                        {
                            xtype: 'button',
                            x: 30,
                            y: 130,
                            text: '确定',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick7,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick7: function(button, e, eOpts) {
        var node=Ext.getCmp('ConTreeView').getSelectionModel().getSelection();
        var n=node[0];
        var cid=n.get('id');

        var fm=Ext.getCmp('submitform').getForm();



        fm.submit({

            url:'/ontotest/addvalofrel',
            params:{ConIdForBody:cid},
            success: function(form,action){

                alert('ok');

            }



        });
    }

});