/*
 * File: app/view/MyWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyWindow', {
    extend: 'Ext.window.Window',

    height: 408,
    width: 511,
    layout: {
        type: 'absolute'
    },
    title: 'My Window',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    x: 90,
                    y: 70,
                    id: 'ontoname',
                    fieldLabel: '本体名'
                },
                {
                    xtype: 'radiogroup',
                    x: 90,
                    y: 140,
                    height: 110,
                    id: 'modelgroup',
                    width: 260,
                    layout: {
                        type: 'vbox'
                    },
                    fieldLabel: '本体模板',
                    items: [
                        {
                            xtype: 'radiofield',
                            id: 'blankonto',
                            name: 'ontomodel',
                            boxLabel: '空白'
                        },
                        {
                            xtype: 'radiofield',
                            id: 'peopleonto',
                            name: 'ontomodel',
                            boxLabel: '人物'
                        },
                        {
                            xtype: 'radiofield',
                            flex: 1,
                            id: 'organizeonto',
                            fieldLabel: '',
                            name: 'ontomodel',
                            boxLabel: '组织'
                        }
                    ]
                },
                {
                    xtype: 'button',
                    x: 210,
                    y: 280,
                    text: '完成',
                    listeners: {
                        click: {
                            fn: me.onButtonClick,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        saveacct=Ext.getCmp('ontoname').getValue();
        Ext.util.Cookies.set('saveacct',saveacct);
        var validStatus = Ext.util.Cookies.get("saveacct");
        alert(validStatus);

        alert('this is a test');
        Ext.Ajax.request( {
            url : '/ontotest/createonto',
            method : 'post',
            params : {
                ontoname : Ext.getCmp('ontoname').getValue(),
                ontomodel : Ext.getCmp('modelgroup').getChecked()[0].getValue()
            },
            success : function(response, options) {
                var o = Ext.util.JSON.decode(response.responseText);
                alert(o.msg);
            },
            failure : function() {
            }
        });
    }

});