/*
 * File: app/view/MyWindow10.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyWindow10', {
    extend: 'Ext.window.Window',

    height: 250,
    id: 'AddRelOfCon2',
    width: 460,
    layout: {
        type: 'absolute'
    },
    title: 'My Window',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'combobox',
                    x: 50,
                    y: 50,
                    id: 'classRel',
                    fieldLabel: '分类属性',
                    store: 'AttTermForClass',
                    listeners: {
                        select: {
                            fn: me.onClassRelSelect,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'combobox',
                    x: 50,
                    y: 110,
                    id: 'className',
                    fieldLabel: '生成的分类为',
                    store: 'AttTermValueForClass'
                },
                {
                    xtype: 'button',
                    x: 170,
                    y: 170,
                    text: '确定添加',
                    listeners: {
                        click: {
                            fn: me.onButtonClick,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'textareafield',
                    x: 320,
                    y: 110,
                    disabled: true,
                    height: 22,
                    id: 'fatherName',
                    width: 110,
                    fieldLabel: ''
                },
                {
                    xtype: 'textareafield',
                    x: 50,
                    y: 10,
                    disabled: true,
                    height: 22,
                    id: 'classCon',
                    fieldLabel: '概念'
                }
            ]
        });

        me.callParent(arguments);
    },

    onClassRelSelect: function(combo, records, eOpts) {

        var node=Ext.getCmp('ConTreeView').getSelectionModel().getSelection();
        var n=node[0];
        var store=Ext.getCmp('className').getStore();
        store.getProxy().url='/ontotest/termsvalforclass';
        //alert(records[0].getData(false).id);
        //alert(Ext.getCmp('classRel').findRecordByValue(Ext.getCmp('classRel').getSubmitValue()).getData(false).id);//alert(record.get('id'));
        store.getProxy().setExtraParam('BodyTreeRelId',records[0].getData(false).id);
        store.getProxy().setExtraParam('ConIdForBody',n.get('id'));
        store.getProxy().setExtraParam('newConTerm',n.get('text'));
        Ext.getCmp('className').clearValue();
        //alert(record.get('id'));
        //store.setRootNode({node:{text:record.get('id')}});

        //alert(store.isLoading());

        //store.load({params:{ConIdForBody:'1000000000'},node:{text:'cid',id:'cid',expanded:false}});
        //alert(Ext.getCmp('ontoGraph'));
        //alert('ok');
        store.load();
    },

    onButtonClick: function(button, e, eOpts) {
        var node=Ext.getCmp('ConTreeView').getSelectionModel().getSelection();
        var n=node[0];

        var relid=Ext.getCmp('classRel').findRecordByValue(Ext.getCmp('classRel').getSubmitValue()).getData(false).id;
        Ext.Ajax.request({
            url:    '/ontotest/addclasscon',
            params: {ConIdForBody:n.get('id'),BodyTreeRelId:relid,newConTerm:n.get('text')},
            method: 'POST',
            callback: function(options,success,response){


                // if(success){n.remove();}
                //else {alert('no');}

            }
        }
        );
    }

});