/*
 * File: app/view/MyWindow8.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyWindow8', {
    extend: 'Ext.window.Window',

    height: 280,
    id: 'renameConTermWin4',
    width: 294,
    layout: {
        type: 'absolute'
    },
    title: 'My Window',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 20,
                    id: 'NewRelTerm',
                    fieldLabel: '关系名'
                },
                {
                    xtype: 'checkboxgroup',
                    x: 10,
                    y: 60,
                    height: 140,
                    id: 'RelProp',
                    width: 200,
                    layout: {
                        type: 'absolute'
                    },
                    fieldLabel: '性质',
                    items: [
                        {
                            xtype: 'checkboxfield',
                            id: 'rfl',
                            boxLabel: '自反性',
                            checked: true
                        },
                        {
                            xtype: 'checkboxfield',
                            x: -1,
                            y: 30,
                            id: 'sym',
                            boxLabel: '对称性'
                        },
                        {
                            xtype: 'checkboxfield',
                            x: 0,
                            y: 60,
                            id: 'inh',
                            fieldLabel: '',
                            boxLabel: '继承性'
                        },
                        {
                            xtype: 'checkboxfield',
                            x: 0,
                            y: 90,
                            id: 'fun',
                            fieldLabel: '',
                            boxLabel: '函数性'
                        },
                        {
                            xtype: 'checkboxfield',
                            x: -1,
                            y: 120,
                            id: 'invfun',
                            fieldLabel: '',
                            boxLabel: '反函数性'
                        }
                    ]
                },
                {
                    xtype: 'button',
                    x: 110,
                    y: 220,
                    text: '确定添加',
                    listeners: {
                        click: {
                            fn: me.onButtonClick,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        //var values=Ext.getCmp('RelProp').getChecked();
        //var v= new Array();

        //var i=0;
        //Ext.Array.each(values,function(item){alert(item[0]);});

        //alert(values.getCount());



        var node=Ext.getCmp('RelTreeView').getSelectionModel().getSelection();
        n=node[0];

        if(n.get('id')!='2000000000') n=node[0].parentNode;

        Ext.Ajax.request({
            url:    '/ontotest/addrel',
            params: {newConTerm: n.get('text'),fatherNode:n.get('id'),newConTermId:null},
            method: 'POST',
            callback: function(options,success,response){

                var obj=Ext.decode(response.responseText);
                n.appendChild({text:obj.newConTerm,id:obj.newConTermId,leaf:true});

                //if(success){Ext.getCmp('ConTreeView').getStore().load();}
                //else {alert('no');}

            }
        }



        );
    }

});