/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'absolute'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    x: 120,
                    y: 40,
                    height: 401,
                    id: 'regform',
                    width: 626,
                    layout: {
                        type: 'absolute'
                    },
                    bodyPadding: 10,
                    title: '本体管理系统注册页面',
                    items: [
                        {
                            xtype: 'textfield',
                            x: 170,
                            y: 80,
                            id: 'username',
                            fieldLabel: '用户名'
                        },
                        {
                            xtype: 'textfield',
                            x: 170,
                            y: 130,
                            id: 'password',
                            fieldLabel: '密码'
                        },
                        {
                            xtype: 'textfield',
                            x: 170,
                            y: 180,
                            id: 'pwdconfirm',
                            fieldLabel: '密码确认'
                        },
                        {
                            xtype: 'textfield',
                            x: 170,
                            y: 240,
                            id: 'email',
                            fieldLabel: 'Email:'
                        },
                        {
                            xtype: 'button',
                            x: 280,
                            y: 310,
                            text: '提交',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        if(Ext.getCmp('password').getValue()==Ext.getCmp('pwdconfirm').getValue()){


            Ext.getCmp('regform').getForm().submit({
                clientValidation: true,

                url: '/ontotest/adduser',

                params: {
                    username: Ext.getCmp('username').getValue(),
                    password: Ext.getCmp('password').getValue(),
                    email: Ext.getCmp('email').getValue()
                },
                success: function(form, action) {
                    Ext.Msg.alert('Success', action.result.msg);

                },
                failure: function(form, action) {
                    switch (action.failureType) {
                        case Ext.form.action.Action.CLIENT_INVALID:
                        Ext.Msg.alert('Failure', 'Form fields may not be submitted with invalid values');
                        break;
                        case Ext.form.action.Action.CONNECT_FAILURE:
                        Ext.Msg.alert('Failure', 'Ajax communication failed');
                        break;
                        case Ext.form.action.Action.SERVER_INVALID:
                        Ext.Msg.alert('Failure', "用户名重复");
                    }
                }
            });




        }
        else{

            alert("密码不一致");

        }
    }

});