/*
 * File: app/store/AttBodyTreeStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.AttBodyTreeStore', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'MyApp.model.treemodel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'MyApp.model.treemodel',
            storeId: 'AttBodyTreeStore',
            root: {
                text: '关系体',
                id: '004'
            },
            proxy: {
                type: 'ajax',
                url: '/ontotest/relbodydata',
                reader: {
                    type: 'json',
                    root: 'conbodyreles'
                }
            },
            listeners: {
                beforeexpand: {
                    fn: me.onTreeStoreBeforeExpand,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onTreeStoreBeforeExpand: function(nodeinterface, eOpts) {
        //alert(nodeinterface.get('text'));
        this.getProxy().url='/ontotest/relasyncdata';
        //alert(nodeinterface.get('id'));
        this.getProxy().extraParams.BodyTreeRelId=nodeinterface.get('id');

        //this.load();
    }

});